## ASSIGNMENT
## THE OVERALL GOAL OF THIS ASSIGNMENT IS TO EXPLORE THE NATIONAL EMMISIONS INVENTORY
## DATABASE AND SEE WHAT IT SAYS ABOUT PARTICULATE MATTER POLLUTION IN THE UNITED STATES
## OVER A TEN YEAR PERIOD 1999-2008. MAKE RELEVANT PLOTS IN ORDER TO ANSWER THE QUESTIONS.

## READ IN THE 2 RDS SUPPLIED FOR THE PROJECT

## QUESTION: HOW HAVE EMISSIONS FROM VEHICLES CHANGED IN BALTIMORE DURING 1999-2008?
## ANSWER: THEY DECREASED SIGNIFICANTLY FROM 1999 TO 2002. THEY DECLINED GRADUALLY FROM
## 2002-2008.

NEI <- readRDS("~/DS mod4 wk4 proj/exdata_data_NEI_data/summarySCC_PM25.rds")  
SCC<- readRDS("~/DS mod4 wk4 proj/exdata_data_NEI_data/Source_Classification_Code.rds")

NEISCC <- merge(NEI, SCC, by="SCC")

## PARSE OUT EMMISSION DATA FOR BALIMORE AND ON-ROAD
BALTNEI <- NEI[NEI$fips=="24510" & NEI$type=="ON-ROAD",]

AGGDATA <- aggregate(Emissions ~ year, BALTNEI, sum)

png("PLOT5.png")

barplot(height=AGGDATA$Emissions, names.arg=AGGDATA$year, xlab="Year", 
        ylab=expression('Total Baltimore vehicle emissions'),col ="turquoise",
        main=expression('Total Baltimore emissions generated by vehicles at various years'))

dev.off()